### ISSUE TITLE
Feature Request: Handle image src attribute swapping

### ISSUE THREAD

**Issue by NeuronButter** [xiaoyang-sde/reflare#308]
**Is your feature request related to a problem? Please describe.**
Setting up a mirror of a site is useful as per the examples, and the `<a href="">` attributes are being swapped as expected, however it would be useful if any `<img src="">` attributes were also proxied.

**Describe the solution you'd like**

For each `<img src="https://original.site/something.png">` found, replace the URL with the host where applicable, so when the host is "original.site", replace it with `mirror.site`.

For each `<img src="https://cdn.original.site/something.png">` found, optionally handle this image, and swap where applicable (some query parameter would have to be set to let Reflare know that it is not the original site, such as `https://mirror.site/something.png?host=cdn.original.site`).

**Describe alternatives you've considered**
Outside of Reflare, I have managed to get this to work with [HTML Rewriter](https://developers.cloudflare.com/workers/runtime-apis/html-rewriter/), swapping all of the image sources with new URLs.

**Comment by xiaoyang-sde** [comment]
Please take a look at https://github.com/xiaoyang-sde/reflare#upstream, which introduces the new callback methods (`onRequest`, `onRespone`) that could replace the path. You could invoke the HTML Rewriter in the `onRespone` callback.
