### ISSUE TITLE
Ability to Replace Path

### ISSUE THREAD

**Issue by sabbirrahman** [xiaoyang-sde/reflare#352]
I have my client at `https://client.mydomain.com` and my API at `https://api.mydomain.com`. I want to serve my API from `https://client.mydomain.com/api/`. The problem is the '/api' part is getting appended to my API url. Hence request to `https://client.mydomain.com/api/products` is trying to serve content from `https://api.mydomain.com/api/product` and resulting in 404. It should serve from `https://api.mydomain.com/product`. Here is my config:
```
{
  path: '/api/*',
  upstream: {
    domain: 'api.mydomain.com',
    protocol: 'https',
  },
}
```
I couldn't find any config option to replace/remove the '/api' part. So, it will be nice to have such feature.
Thank you.

**Comment by omerzam** [comment]
this is a great enhancement!
any idea when is this going to be published to npm?

**Comment by xiaoyang-sde** [comment]
> this is a great enhancement!
> any idea when is this going to be published to npm?

Yeah I’m planning to release an update this week.

**Comment by xiaoyang-sde** [comment]
@hanford @omerzam @sabbirrahman
v1.1.0 has been released! Please take a look at https://github.com/xiaoyang-sde/reflare#upstream, which introduces the new callback methods (`onRequest`, `onRespone`) that could replace the path.
