### ISSUE TITLE
Can I use it with serverless function like aws lambda?

### ISSUE THREAD

**Issue by chocolatedesue** [xiaoyang-sde/reflare#372]
I find this is an amazing works.

But I am confused when I try to use it with other serverless like aws lambda.

Can the reverse proxy be triggered by http request?

**Comment by xiaoyang-sde** [comment]
Well this proxy is written for Cloudflare Workers. I don’t think it supports AWS Lambda now.

**Comment by chocolatedesue** [comment]
Thanks, I got it
