### ISSUE TITLE
Allow streaming responses

### ISSUE THREAD

**Issue by chitalian** [xiaoyang-sde/reflare#443]
**Is your feature request related to a problem? Please describe.**
Would love the ability to have a complete pass-through where we can easily add a logging solution and still support streaming responses.
Something like this
https://developers.cloudflare.com/workers/learning/using-streams/
```typescript
const [readable, readableLog] = response.body?.tee()
ctx.waitUntil(logResponss(readableLog));
return new Response(readable, {
    ...response,
})
```

**Describe the solution you'd like**
 I would love a way to easily incorporate streaming into reflare, where we can maybe add a config and the response is streamed back but there is a handler for the readableLog.

**Describe alternatives you've considered**
N/A

**Additional context**
I haven't looked too much into your code base to see if this is possible, but i did a quick look. We are looking to add this for Helicone.ai, and we currently handrolled our own version of this pacakge, before just learning about it now

**Comment by xiaoyang-sde** [comment]
Thanks for the suggestion! I will take a look.

**Comment by xiaoyang-sde** [comment]
I have reviewed the related documentation about streaming and I agree that it is possible to implement this feature. However, as the final week is approaching, I cannot promise a definite timeline for when I can complete the work.

**Comment by xiaoyang-sde** [comment]
If my understanding is correct, when a response is fetched from the upstream and returned without modifications to its content (that's the behavior of reflare), it is streamed back to the client.

Therefore, the feature I need to implement is to clone the stream and pass it to a custom logging function?

**Comment by chitalian** [comment]
oh yeah @xiaoyang-sde that totally works! Thanks for following up here, for some reason I had imagined this would be more complicated.

**Comment by xiaoyang-sde** [comment]
No worries! I saw your post about your startup on Hacker News today. Let me know if you have other questions.
