### ISSUE TITLE
how to use async function in OnResponse

### ISSUE THREAD

**Issue by billzhuang** [xiaoyang-sde/reflare#473]
hi,
for example, I want to add some words end of original body, I can't use await response.text(), since OnResponse is an synconaize method. 

how I can get the body text itself?

**Comment by xiaoyang-sde** [comment]
The latest commit supports `async` callback functions for both request and response: https://github.com/xiaoyang-sde/reflare/blob/master/src/middlewares/upstream.ts#L54-L67

**Comment by billzhuang** [comment]
AWESOME! Thanks.
